#!/usr/bin/env sh

# Primary Colors
export ORANGE=0xFFFA8F69          #0xFF9164

export NAVY_BLUE=0xFF2B4D7E       #0x2B4D7E
export MIDNIGHT_BLUE=0xFF13294B   #0x13294B

# Supporting Colors
export WHITE=0xFFE1E3E9           #0xE1E3E9
export WARM_GRAY=0xFF9CA0B0       #0x9CA0B0
export DARK_INK=0xFF1F2133        #0x1F2133
export SHADOW_GRAY=0xCC1E2030     #0x1E2030

#################### Bar Colors ######################
export BAR_COLOR=$SHADOW_GRAY
export ICON_COLOR=$WHITE
export LABEL_COLOR=$WHITE

#################### Front App Colors ################
export FRONT_APP_ICON=$WHITE
export FRONT_APP_LABEL=$WHITE

export FRONT_APP_POPUP_BACKGROUND=$MIDNIGHT_BLUE
export FRONT_APP_POPUP_ICON=$WARM_GRAY
export FRONT_APP_POPUP_LABEL=$WARM_GRAY

export POPUP_SELECTED_ICON=$ORANGE
export POPUP_SELECTED_LABEL=$ORANGE

#################### Space Colors ####################
export SPACE_SELECTED=$ORANGE
export SPACE_ICON_SELECTED=$DARK_INK
export SPACE_LABEL_SELECTED=$DARK_INK

export SPACE_ALT_SELECTED=$NAVY_BLUE
export SPACE_ALT_ICON_SELECTED=$WARM_GRAY
export SPACE_ALT_LABEL_SELECTED=$WARM_GRAY

export SPACE_DESELECTED=$MIDNIGHT_BLUE
export SPACE_ICON_DESELECTED=$WARM_GRAY
export SPACE_LABEL_DESELECTED=$WARM_GRAY

#################### Windows Colors ####################
export MONITOR_1_BACKGROUND=$ORANGE
export MONITOR_1_ICON=$DARK_INK
export MONITOR_1_LABEL=$DARK_INK

export MONITOR_2_BACKGROUND=$NAVY_BLUE
export MONITOR_2_ICON=$WHITE
export MONITOR_2_LABEL=$WHITE

export WINDOW_ITEM_BACKGROUND=$MIDNIGHT_BLUE
export WINDOW_ITEM_ICON=$WARM_GRAY
export WINDOW_ITEM_LABEL=$WARM_GRAY