#!/usr/bin/env sh

PLUGIN_DIR="$CONFIG_DIR/plugins"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar position=top height=40 blur_radius=30 color=0x40000000

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=1
  padding_right=1
  icon.font="Hack Nerd Font:Bold:14.0"
  label.font="Hack Nerd Font:Bold:14.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.padding_left=2
  icon.padding_right=4
  label.padding_left=2
  label.padding_right=2
  updates=on
)
sketchybar --default "${default[@]}"

##### Adding AeroSpace Workspace Indicators #####
sketchybar --add event aerospace_workspace_change

AEROSPACE_NUM_MONITORS=$(aerospace list-monitors | wc -l)
AEROSPACE_WORKSPACES=$(aerospace list-workspaces --all)
AEROSPACE_CURR_WORKSPACE=$(aerospace list-workspaces --focused)

EMPTY_WORKSPACES=$(. "$PLUGIN_DIR/workspace_utils.sh" && get_empty_workspaces)

# First loop for empty workspaces
for sid in $AEROSPACE_WORKSPACES; do
  # is_active_background=$( [ "$sid" = "$AEROSPACE_CURR_WORKSPACE" ] && echo "on" || echo "off" )
  # # Check if current workspace is in empty workspaces list
  # is_empty_workspace=$( [[ $EMPTY_WORKSPACES =~ (^|[[:space:]])$sid($|[[:space:]]) ]] && echo "off" || echo "on" )
  # # Debug statement
  # echo "Workspace $sid - Empty: $([[ $is_empty_workspace == "off" ]] && echo "yes" || echo "no")"

  # # Initialize empty workspace properties
  # empty_workspace_props=()
  # if [[ $is_empty_workspace == "off" && $is_active_background == "off" ]]; then
  #   empty_workspace_props=(
  #     icon.drawing=off
  #     label.drawing=off
  #     padding_left=0
  #     padding_right=0
  #   )
  # fi
  is_active_background=$( [ "$sid" = "$AEROSPACE_CURR_WORKSPACE" ] && echo "on" || echo "off" )
  is_empty_workspace=$(. "$PLUGIN_DIR/workspace_utils.sh" && is_workspace_empty "$sid" "$EMPTY_WORKSPACES")

  # Initialize empty workspace properties
  empty_workspace_props=($(. "$PLUGIN_DIR/workspace_utils.sh" && get_workspace_properties "$sid" "$is_empty_workspace" "$is_active_background"))

  props=(
    background.color=0x44ffffff
    background.corner_radius=5
    background.height=20
    background.drawing=$is_active_background
    icon="$sid"
    label.font="sketchybar-app-font:Regular:12.0"
    label.padding_right=20
    # label.padding_left=5
    label.drawing=off
    click_script="aerospace workspace $sid"
    script="$CONFIG_DIR/plugins/aerospace.sh $sid"
    "${empty_workspace_props[@]}"
  )

  sketchybar --add item space.$sid left \
      --subscribe space.$sid aerospace_workspace_change \
      --set space.$sid "${props[@]}"
done

# Get non-empty workspaces by filtering out empty ones
echo "$AEROSPACE_WORKSPACES" | tr ' ' '\n' | sort > /tmp/all_workspaces
echo "$EMPTY_WORKSPACES" | tr ' ' '\n' | sort > /tmp/empty_workspaces
NON_EMPTY_WORKSPACES=$(comm -23 /tmp/all_workspaces /tmp/empty_workspaces)
rm /tmp/all_workspaces /tmp/empty_workspaces

# Loop through non-empty workspaces to load icons
for sid in $NON_EMPTY_WORKSPACES; do
  echo "DEBUG: $sid"
  apps=$(aerospace list-windows --workspace "$sid" | awk -F'|' '{gsub(/^ *| *$/, "", $2); print $2}')

  # sketchybar --set space.$sid drawing=on

  icon_strip=" "
  if [ "${apps}" != "" ]; then
    while read -r app; do
      icon_strip+=" $($CONFIG_DIR/plugins/icon_map_fn.sh "$app")"
    done <<<"${apps}"
  else
    icon_strip="-"
  fi
  echo "DEBUG: $sid $icon_strip"
  sketchybar --set space.$sid drawing=on label="$icon_strip" label.drawing=on
done

##### Adding Left Items #####
# We add some regular items to the left side of the bar, where
# only the properties deviating from the current defaults need to be set

sketchybar --add item chevron left \
           --set chevron icon= label.drawing=off \
           --add item front_app left \
           --set front_app icon.drawing=off script="$PLUGIN_DIR/front_app.sh" \
           --subscribe front_app front_app_switched

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

sketchybar --add item clock right \
           --set clock update_freq=10 icon=  script="$PLUGIN_DIR/clock.sh" \
           --add item volume right \
           --set volume script="$PLUGIN_DIR/volume.sh" \
           --subscribe volume volume_change \
           --add item battery right \
           --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
           --subscribe battery system_woke power_source_change

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
